### PR TITLE
using odinsmr dockerhub registry

### LINKED ISSUE #2: (3) script for starting a new processing project seems to be broken
Error message from Francesco below:
```
francesco@coral:~/work/qsmr/Build_scripts$ sudo ./create_qsmr_project.sh test_meso_19_ab.ini -s 2019-05-01 -e 2020-11-04 -d 2020-11-07
Create worker image!
Project name MESO19SB110ALL19lowTunc4 is valid.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  237k  100  237k    0     0  57.9M      0 --:--:-- --:--:-- --:--:-- 57.9M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  272k  100  272k    0     0  66.5M      0 --:--:-- --:--:-- --:--:-- 66.5M
Sending build context to Docker daemon  103.7MB
Step 1/15 : FROM docker2.molflow.com/devops/arts:10134 AS builder
 ---> c4af70cec7a9
Step 2/15 : COPY data /QsmrData
 ---> aceb45255fba
Step 3/15 : COPY qsmr_precalc.tar.gz /qsmr_precalc/qsmr_precalc.tar.gz
 ---> 7b0a9905acc8
Step 4/15 : RUN set -x && cd /qsmr_precalc &&     tar xf qsmr_precalc.tar.gz &&     rm qsmr_precalc.tar.gz
 ---> Running in 7b3632842435
+ cd /qsmr_precalc
+ tar xf qsmr_precalc.tar.gz
+ rm qsmr_precalc.tar.gz
Removing intermediate container 7b3632842435
 ---> b6ba399377ff
Step 5/15 : ENV LD_LIBRARY_PATH /opt/matlab/v90/runtime/glnxa64:/opt/matlab/v90/bin/glnxa64:/opt/matlab/v90/sys/os/glnxa64
 ---> Running in 41b981119dcd
Removing intermediate container 41b981119dcd
 ---> 806bc9d80ac1
Step 6/15 : COPY build_data_artifact.sh /build_data_artifact.sh
 ---> 7c87c5640aee
Step 7/15 : RUN chmod u+x /build_data_artifact.sh
 ---> Running in 55ca3f2f972d
Removing intermediate container 55ca3f2f972d
 ---> 35f657ecb98c
Step 8/15 : RUN /build_data_artifact.sh /QsmrData meso 19
 ---> Running in 0c3ae4685e9b
Building data artifact for invemode meso and freqmode 19
------------------------------------------
Setting up environment variables
---
LD_LIBRARY_PATH is .:/opt/matlab/v90/runtime/glnxa64:/opt/matlab/v90/bin/glnxa64:/opt/matlab/v90/sys/os/glnxa64:/opt/matlab/v90/sys/opengl/lib/glnxa64
Using Q config with freqmode 19 and invmode meso
Removing intermediate container 0c3ae4685e9b
 ---> 560252e716d9
Step 9/15 : RUN rm -r /QsmrData/DataInput
 ---> Running in 803aca1f914b
Removing intermediate container 803aca1f914b
 ---> e71f57667e32
Step 10/15 : FROM docker2.molflow.com/devops/arts:10134
 ---> c4af70cec7a9
Step 11/15 : COPY qsmr.tar.gz /qsmr/qsmr.tar.gz
 ---> db51c5c93fcc
Step 12/15 : RUN set -x &&     cd /qsmr &&     tar xf qsmr.tar.gz &&     rm qsmr.tar.gz
 ---> Running in 5317f42ab6bc
+ cd /qsmr
+ tar xf qsmr.tar.gz
+ rm qsmr.tar.gz
Removing intermediate container 5317f42ab6bc
 ---> 9f92aa81910a
Step 13/15 : COPY --from=builder /QsmrData /QsmrData
 ---> 74fa0c280cf7
Step 14/15 : ENV LD_LIBRARY_PATH /opt/matlab/v90/runtime/glnxa64:/opt/matlab/v90/bin/glnxa64:/opt/matlab/v90/sys/os/glnxa64
 ---> Running in 44fbde16a26b
Removing intermediate container 44fbde16a26b
 ---> 7f194cfc588e
Step 15/15 : ENTRYPOINT ["/qsmr/run_runscript.sh", "/opt/matlab/v90"]
 ---> Running in 6671aeb52e33
Removing intermediate container 6671aeb52e33
 ---> e3608cdc461b
Successfully built e3608cdc461b
Successfully tagged molflow/u-jobs:qsmr_meso_19_MESO19SB110ALL19lowTunc4_201104
The push refers to repository [docker.io/molflow/u-jobs]
2b175ad37a48: Preparing
de0d4b96c25a: Preparing
5c52bff4e23b: Preparing
4f7a79186c9f: Preparing
89880575e0de: Preparing
f96222d75c55: Waiting
denied: requested access to the resource is denied
succesfully built and pushed image molflow/u-jobs:qsmr_meso_19_MESO19SB110ALL19lowTunc4_201104
Adding all between 2019-05-01 and 2020-11-04
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/microq_admin/__main__.py", line 47, in <module>
    exit(qsmrjobs.main(_service_args, prog=_service_name))
  File "/app/microq_admin/jobsgenerator/qsmrjobs.py", line 97, in main
    return int(not adder.add_jobs(ids, freqmode, skip=skip))
  File "/app/microq_admin/jobsgenerator/qsmrjobs.py", line 163, in add_jobs
    scanids, freqmode, skip)
  File "/app/microq_admin/jobsgenerator/qsmrjobs.py", line 194, in filter_jobs
    for i, scanid in enumerate(scanids):
  File "/app/microq_admin/jobsgenerator/scanids.py", line 75, in generate_all
    for _, url, _ in days:
  File "/app/microq_admin/jobsgenerator/scanids.py", line 113, in generate_days_with_scans
    for day in data['Data']
  File "/app/microq_admin/jobsgenerator/scanids.py", line 116, in <listcomp>
    day['Date'], '%a, %d %b %Y %H:%M:%S GMT'
  File "/usr/local/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2019-09-02' does not match format '%a, %d %b %Y %H:%M:%S GMT'
```

### PR DESCRIPTION
**Pull request by BengtRydberg**
the script for building worker images now using odinsmr dockerhub registry.

I have one more PR in a different repo.
https://github.com/molflow/docker/pull/2
that fixes the building of the base image used here, as this was broken.

I have tested that the current PR manage to build a new worker image
using the base image built by in the other PR, so it looks like this
should work.

Resolves #2

### CODE REVIEW

File: Build_scripts/docker/build_worker_image.sh [hunk 1]
```diff
@@ -42,7 +42,7 @@ IMG_TAG=$3
 
 create_docker_file $INVEMODE $FREQMODE
 
-registry="molflow/u-jobs"
+registry="odinsmr/u-jobs"
```
Comment (skymandr) [inline Build_scripts/docker/build_worker_image.sh:45]: Is this one also in `odinsmr`?

**Review by skymandr — APPROVED** [review]
I assume you've verified all paths. Looks good, but perhaps make sure it works after the other PR is done, before merging.

File: Build_scripts/docker/build_worker_image.sh (hunk 1 above)
Comment (BengtRydberg) [reply Build_scripts/docker/build_worker_image.sh:45]: yes, at least it should.

File: Build_scripts/docker/build_worker_image.sh [hunk 2]
```diff
@@ -23,7 +23,7 @@ RUN chmod u+x /build_data_artifact.sh
 RUN /build_data_artifact.sh /QsmrData ${INVEMODE} ${FREQMODE}
 RUN rm -r /QsmrData/DataInput
 
-FROM odinsmr/arts:10134
+FROM odinsmr/arts:2.3.564
```
Comment (local-minimum) [inline Build_scripts/docker/build_worker_image.sh:26]: är inte tanken här att man borde kunna ha `FROM builder` eller jag kanske inte förstår tankten i filen.

Comment (skymandr) [reply Build_scripts/docker/build_worker_image.sh:26]: tror @joakimmoller är den som bäst kan svara på det.

**Review by skymandr — COMMENTED** [review]
Check with @joakimmoller regarding the comment by @local-minimum, other than that it looks good.

File: Build_scripts/docker/build_worker_image.sh (hunk 2 above)
Comment (joakimmoller) [reply Build_scripts/docker/build_worker_image.sh:26]: Nej det är ju två helt separata byggen, men båda börjar på samma basimage. Det senare bygget tar sedan en fil från det första bygget då används "copy  --from=builder"

Comment (local-minimum) [reply Build_scripts/docker/build_worker_image.sh:26]: 🆗
